PROD OCP notification
BCDevOps/platform-services-status-page-notifications pull request #100
Opened 2020-10-28 20:43 UTC by tbaker1313

Notification for the upcoming OCP update in 3.11 PROD

2020-10-28 22:14 UTC, sbarre-esit requested changes
Can we copy in some of the more detailed "will there be an impact" section from last quarter?

https://github.com/BCDevOps/platform-services-status-page-notifications/pull/90/files#diff-4c0c45d3014c1b69438ff687c2eadc3069d4afe05f89f8ef67a1f00144c368e5

2020-10-28 22:19 UTC, tbaker1313 commented
Added desired impact section.

2020-10-28 23:50 UTC, sbarre-esit approved these changes

2020-10-30 22:01 UTC, tbaker1313 commented
Posted manually. For some reason this didn't merge as expected so will close.

2020-10-30 22:01 UTC, closed without merging